const typeCodes = [
    [0,'custom'],
    [1,'ascii'],
    [2,'bigint'],
    [3,'blob'],
    [4,'boolean'],
    [5,'counter'],
    [6,'decimal'],
    [7,'double'],
    [8,'float'],
    [9,'int'],
    [10,'text'],
    [11,'timestamp'],
    [12,'uuid'],
    [13,'varchar'],
    [14,'varint'],
    [15,'timeuuid'],
    [16,'inet'],
    [17,'date'],
    [18,'time'],
    [19,'smallint'],
    [20,'tinyint'],
    [32,'list'],
    [33,'map'],
    [34,'set'],
    [48,'udt'],
    [49,'tuple'],
];

module.exports = new Map(typeCodes);